"""Agregar asesor, foreign key en leads y eliminar estado en leads

Revision ID: c6193c348384
Revises: ec115f450f53
Create Date: 2026-07-08 00:51:09.859064

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6193c348384'
down_revision: Union[str, Sequence[str], None] = 'ec115f450f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesor',
    sa.Column('id_asesor', sa.Uuid(), nullable=False),
    sa.Column('nombre_asesor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_asesor')
    )
    op.add_column('leads', sa.Column('asesor_encargado', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'leads', 'asesor', ['asesor_encargado'], ['id_asesor'])
    op.drop_column('leads', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'asesor_encargado')
    op.drop_table('asesor')
    # ### end Alembic commands ###
