"""esquema inicial

Revision ID: ec115f450f53
Revises: 
Create Date: 2026-06-28 03:05:31.322415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec115f450f53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones',
    sa.Column('id_conversacion', sa.Uuid(), nullable=False),
    sa.Column('canal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canal_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conv_actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_conversacion')
    )
    op.create_table('productos',
    sa.Column('id_woocommerce', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_regular', sa.Numeric(), nullable=False),
    sa.Column('precio_venta', sa.Numeric(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_woocommerce')
    )
    op.create_table('leads',
    sa.Column('id_lead', sa.Uuid(), nullable=False),
    sa.Column('id_conversacion', sa.Uuid(), nullable=False),
    sa.Column('productos_interes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lead_creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conversacion'], ['conversaciones.id_conversacion'], ),
    sa.PrimaryKeyConstraint('id_lead')
    )
    op.create_table('mensajes',
    sa.Column('id_mensaje', sa.Uuid(), nullable=False),
    sa.Column('id_conversacion', sa.Uuid(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conversacion'], ['conversaciones.id_conversacion'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes')
    op.drop_table('leads')
    op.drop_table('productos')
    op.drop_table('conversaciones')
    # ### end Alembic commands ###
